{% set version = "4.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vim
  version: {{ version|replace("-", "_") }}

source:
  fn: VIM_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/VIM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/VIM/VIM_{{ version }}.tar.gz
  sha256: 3c6b4fdc10c0375e3fdc56b34a8c05661155bd3166a8b3f36b0addf73d51a423

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-car
    - r-colorspace
    - r-data.table >=1.9.4
    - r-e1071
    - r-laeken
    - r-nnet
    - r-ranger
    - r-robustbase
    - r-sp
    - r-vcd
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-rcpp
    - r-car
    - r-colorspace
    - r-data.table >=1.9.4
    - r-e1071
    - r-laeken
    - r-nnet
    - r-ranger
    - r-robustbase
    - r-sp
    - r-vcd

test:
  commands:
    - $R -e "library('VIM')"           # [not win]
    - "\"%R%\" -e \"library('VIM')\""  # [win]

about:
  home: https://github.com/statistikat/VIM
  license: GPL (>= 2)
  summary: New tools for the visualization of missing and/or imputed values are introduced, which
    can be used for exploring the data and the structure of the missing and/or imputed
    values. Depending on this structure of the missing values, the corresponding methods
    may help to identify the mechanism generating the missing values and allows to explore
    the data including missing values. In addition, the quality of imputation can be
    visually explored using various univariate, bivariate, multiple and multivariate
    plot methods. A graphical user interface available in the separate package VIMGUI
    allows an easy handling of the implemented plot methods.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
