appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bWByA+7RTSCq5e0XssVNDiUtD6LgA5v3YdSm8aLDpQT76FYCrDKdhG3yWtpOTchqdCNJHBNF2vHfRy2KV3/KicHNqjwFWr2kbiedr+ikg+yQ1Pe24xYij4M2r2Em+q/UgY2LXVnhlTlmZ2dPFvVNwfUdoAhTyfzXtTApSOo+fpX/3Mu0JLMXf60nrDJARHUt5iYWsqnNfOMD9nl45ETF98U/OYQMJcfLn3CS7MiWbw6h0l6CA8FCtlOWWHoyymC6xg6NoYRGmGQ2pzLjRCE2U/WYFyPl5b6wsDCZrS/lyjCvdndQkCNJ1ev3gRNFRmb6jN7uz1cXU8QAkFhUdhstWgAvSv2ePHFRQbuIpAidgtYUn0a+XiKTnk2bGQA2gPpnBr7ZHX7LB/F+vHDZZP4NgtWbla2TSlJAfLmVHypUN/G4okMEs0R8u+Pf5pRgdQWIA+Sg3YSaz5R57tGrRDCz5qW46R12JcCq7/qf7qR8hMbAVKzy8lR6O0urPex5/hKU4Y+/cm9C5qxwgYCTP+TpmqT7IUgx4S2LiXaHMtABlWOh/j0JURGhx+pcPQwpvE/ETOmCUdMk7TZmPoLq2LqURpvlt0kG8FXacL9AVJPS7lgnGiIrFXrzmgcGr4Tcqe/vg0PZbYdGRPyzbUwLbqAZjCRNzm0VNsEJswCl520Ez4k=}
