travis:
  secure:
    BINSTAR_TOKEN: gpLFi00gYccNHo4s/F1m9u+GdtSWsBjfSEGll1P/iUlSUb9tVUsfsKB2Sjd3q8BBc4VNLlvKZkxUY6ya7cNKOknl35kpJdiOYG7IvPDYfUJJk5mkz1G3aQkTCFGySE5CYjpt6AdNLkCpklzHoUcZgiy7aULwPF2+un7JREpW3wG5OYfFQpjl02XwebfzPzbKHzzcNfZvRsaRXtYFyvgiPQwreDYLQrlJc9utp9PDlOAgafTdp96Ay8G2ylUlfRTOpdhv90fH1+cacoSQhWDBInqZ1KotIHvxqNlCEBoB9HegzUPMqZrkQNXEQdRBeiJRgmOyOIZ6Gih0ifSX9QFH1RauhgGipbZlY5hVwvs/wWGllDP59uT71bGLlI9bh5amhTRqupXsQIUOMU9eonMCnoVP64i5EydRG7Vy9kluMHzbUtI/kKSus+L/i19dej/joFTR0nmwhA/kfoyIECCDafjlh+glvi7I1z6xbIR59srLGW8kAegd9Q0XNtKqwNALfcjiD5s/WEi5yTEH4RZE3zF3cA2jA49l7hnLa86AarODxpvo6u9lI//MCHch+L871cKjeg4B7EjPxtFGoNYD6Z2owQZgM4v70D7rvecVfdm5dEHFcq6mQN4FHzMW3Fs2b0BljzOPNLY9LzAQry1tsc96l74EjsppptE85jm3SVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
